---
- hosts: all
  become: true
  roles:
  - all
  - role: ericsysmin.chrony
    chrony_config_server:
      - mickey.lss.emc.com

- hosts: gateway
  vars_files:
    - roles/all/vars/vars.yml
  become: true
  roles:
  - gateway

- hosts: master
  become: true
  roles:
  - master

- hosts: tiebreaker
  become: true
  roles:
  - tiebreaker

