---
- hosts: all
  become: true
  vars_files:
    - ./vars.yml
  roles:
  - all
  - role: ericsysmin.chrony
    chrony_config_server:
      - "{{ ntp_server }}"

- hosts: gateway
  become: true
  vars_files:
    - ./vars.yml
  roles:
  - gateway

- hosts: master
  become: true
  vars_files:
    - ./vars.yml
  roles:
  - master

- hosts: tiebreaker
  become: true
  vars_files:
    - ./vars.yml
  roles:
  - tiebreaker

