- name: "Installing Basic Tools"
  package: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - git
  - vim
  - libaio
  - numactl
  - sysfsutils
  - unzip
  - wget
  - net-tools

- name: set timezone to UTC
  timezone:
    name: UTC
    hwclock: UTC

- name: "Copy RHEL 7 SIO Files"
  copy:
    src: ./sio_packages/
    dest: /tmp/
    owner: root
    group: root
    mode: 0644


