- name: "Install SIO SDS"
  yum:
    name: '/tmp/sio_packages/EMC-ScaleIO-sds-{{ vxflex_version }}.x86_64.rpm'
    state: present

- name: "Install SIO LIA"
  yum:
    name: '/tmp/sio_packages/EMC-ScaleIO-lia-{{ vxflex_version }}.x86_64.rpm'
    state: present


- name: "Install MDM and set the host to Master"
  yum:
    name: '/tmp/SIO_Packages/EMC-ScaleIO-mdm-{{ vxflex_version }}.x86_64.rpm'
    state: present
  environment:
    MDM_ROLE_IS_MANAGER: 1

